AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MwaaEnvironment:
    Type: "AWS::MWAA::Environment"
    Properties: 
      AirflowConfigurationOptions: 
        core.default_timezone: utc
        logging.logging_level: INFO
      DagS3Path: dags
      EnvironmentClass: mw1.large
      ExecutionRoleArn: "arn:aws:iam::179773146609:role/service-role/AmazonMWAA-MyAirflowEnvironment-GZFTyP"
      LoggingConfiguration: 
        DagProcessingLogs: 
          Enabled: true
          LogLevel: INFO
        SchedulerLogs: 
          Enabled: false
          LogLevel: INFO
        TaskLogs: 
          Enabled: true
          LogLevel: INFO
        WebserverLogs: 
          Enabled: false
          LogLevel: INFO
        WorkerLogs: 
          Enabled: false
          LogLevel: INFO
      MaxWorkers: 1
      Name: MWAApoc
      NetworkConfiguration: 
        SecurityGroupIds: 
          - sg-04ded70fb860ff04f
        SubnetIds: 
          - subnet-01166abeafa4be6dd
          - subnet-0ea5e635e30b743e6
      SourceBucketArn: "arn:aws:s3:::dags-poc"
      WebserverAccessMode: PUBLIC_ONLY
     # KmsKey: "arn:aws:kms:us-east-1:753920291680:key/698be251-5a5a-4885-a9ff-d6e7cc59dd14"
      Tags: 
        env: dev
